#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="rvs")]
	public partial class ORMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcita(cita instance);
    partial void Updatecita(cita instance);
    partial void Deletecita(cita instance);
    partial void Insertciudad(ciudad instance);
    partial void Updateciudad(ciudad instance);
    partial void Deleteciudad(ciudad instance);
    partial void Insertenfermedad(enfermedad instance);
    partial void Updateenfermedad(enfermedad instance);
    partial void Deleteenfermedad(enfermedad instance);
    partial void Insertente_salud(ente_salud instance);
    partial void Updateente_salud(ente_salud instance);
    partial void Deleteente_salud(ente_salud instance);
    partial void Insertespecialidad(especialidad instance);
    partial void Updateespecialidad(especialidad instance);
    partial void Deleteespecialidad(especialidad instance);
    partial void Insertespecialista(especialista instance);
    partial void Updateespecialista(especialista instance);
    partial void Deleteespecialista(especialista instance);
    partial void Inserthora_cita(hora_cita instance);
    partial void Updatehora_cita(hora_cita instance);
    partial void Deletehora_cita(hora_cita instance);
    partial void Insertpersona(persona instance);
    partial void Updatepersona(persona instance);
    partial void Deletepersona(persona instance);
    partial void Insertrecomendacion(recomendacion instance);
    partial void Updaterecomendacion(recomendacion instance);
    partial void Deleterecomendacion(recomendacion instance);
    partial void Insertrol(rol instance);
    partial void Updaterol(rol instance);
    partial void Deleterol(rol instance);
    partial void Insertsintoma(sintoma instance);
    partial void Updatesintoma(sintoma instance);
    partial void Deletesintoma(sintoma instance);
    partial void Insertsintoma_enfermedad(sintoma_enfermedad instance);
    partial void Updatesintoma_enfermedad(sintoma_enfermedad instance);
    partial void Deletesintoma_enfermedad(sintoma_enfermedad instance);
    #endregion
		
		public ORMDataContext() : 
				base(global::Modelo.Properties.Settings.Default.rvsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cita> cita
		{
			get
			{
				return this.GetTable<cita>();
			}
		}
		
		public System.Data.Linq.Table<ciudad> ciudad
		{
			get
			{
				return this.GetTable<ciudad>();
			}
		}
		
		public System.Data.Linq.Table<enfermedad> enfermedad
		{
			get
			{
				return this.GetTable<enfermedad>();
			}
		}
		
		public System.Data.Linq.Table<ente_salud> ente_salud
		{
			get
			{
				return this.GetTable<ente_salud>();
			}
		}
		
		public System.Data.Linq.Table<especialidad> especialidad
		{
			get
			{
				return this.GetTable<especialidad>();
			}
		}
		
		public System.Data.Linq.Table<especialista> especialista
		{
			get
			{
				return this.GetTable<especialista>();
			}
		}
		
		public System.Data.Linq.Table<hora_cita> hora_cita
		{
			get
			{
				return this.GetTable<hora_cita>();
			}
		}
		
		public System.Data.Linq.Table<persona> persona
		{
			get
			{
				return this.GetTable<persona>();
			}
		}
		
		public System.Data.Linq.Table<recomendacion> recomendacion
		{
			get
			{
				return this.GetTable<recomendacion>();
			}
		}
		
		public System.Data.Linq.Table<rol> rol
		{
			get
			{
				return this.GetTable<rol>();
			}
		}
		
		public System.Data.Linq.Table<sintoma> sintoma
		{
			get
			{
				return this.GetTable<sintoma>();
			}
		}
		
		public System.Data.Linq.Table<sintoma_enfermedad> sintoma_enfermedad
		{
			get
			{
				return this.GetTable<sintoma_enfermedad>();
			}
		}
		
		public System.Data.Linq.Table<VistaEnfermedad> VistaEnfermedad
		{
			get
			{
				return this.GetTable<VistaEnfermedad>();
			}
		}
		
		public System.Data.Linq.Table<VistaEspecialista> VistaEspecialista
		{
			get
			{
				return this.GetTable<VistaEspecialista>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public ISingleResult<sp_loginResult> sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasenia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, contrasenia);
			return ((ISingleResult<sp_loginResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cita")]
	public partial class cita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cita;
		
		private int _id_persona;
		
		private int _id_especialista;
		
		private System.DateTime _fecha_cita;
		
		private int _id_hora;
		
		private System.Nullable<int> _calificacion;
		
		private string _estado;
		
		private EntityRef<especialista> _especialista;
		
		private EntityRef<hora_cita> _hora_cita;
		
		private EntityRef<persona> _persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_citaChanging(int value);
    partial void Onid_citaChanged();
    partial void Onid_personaChanging(int value);
    partial void Onid_personaChanged();
    partial void Onid_especialistaChanging(int value);
    partial void Onid_especialistaChanged();
    partial void Onfecha_citaChanging(System.DateTime value);
    partial void Onfecha_citaChanged();
    partial void Onid_horaChanging(int value);
    partial void Onid_horaChanged();
    partial void OncalificacionChanging(System.Nullable<int> value);
    partial void OncalificacionChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public cita()
		{
			this._especialista = default(EntityRef<especialista>);
			this._hora_cita = default(EntityRef<hora_cita>);
			this._persona = default(EntityRef<persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cita", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_cita
		{
			get
			{
				return this._id_cita;
			}
			set
			{
				if ((this._id_cita != value))
				{
					this.Onid_citaChanging(value);
					this.SendPropertyChanging();
					this._id_cita = value;
					this.SendPropertyChanged("id_cita");
					this.Onid_citaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persona", DbType="Int NOT NULL")]
		public int id_persona
		{
			get
			{
				return this._id_persona;
			}
			set
			{
				if ((this._id_persona != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_personaChanging(value);
					this.SendPropertyChanging();
					this._id_persona = value;
					this.SendPropertyChanged("id_persona");
					this.Onid_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especialista", DbType="Int NOT NULL")]
		public int id_especialista
		{
			get
			{
				return this._id_especialista;
			}
			set
			{
				if ((this._id_especialista != value))
				{
					if (this._especialista.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_especialistaChanging(value);
					this.SendPropertyChanging();
					this._id_especialista = value;
					this.SendPropertyChanged("id_especialista");
					this.Onid_especialistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cita", DbType="Date NOT NULL")]
		public System.DateTime fecha_cita
		{
			get
			{
				return this._fecha_cita;
			}
			set
			{
				if ((this._fecha_cita != value))
				{
					this.Onfecha_citaChanging(value);
					this.SendPropertyChanging();
					this._fecha_cita = value;
					this.SendPropertyChanged("fecha_cita");
					this.Onfecha_citaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hora", DbType="Int NOT NULL")]
		public int id_hora
		{
			get
			{
				return this._id_hora;
			}
			set
			{
				if ((this._id_hora != value))
				{
					if (this._hora_cita.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_horaChanging(value);
					this.SendPropertyChanging();
					this._id_hora = value;
					this.SendPropertyChanged("id_hora");
					this.Onid_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Int")]
		public System.Nullable<int> calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="especialista_cita", Storage="_especialista", ThisKey="id_especialista", OtherKey="id_especialista", IsForeignKey=true)]
		public especialista especialista
		{
			get
			{
				return this._especialista.Entity;
			}
			set
			{
				especialista previousValue = this._especialista.Entity;
				if (((previousValue != value) 
							|| (this._especialista.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._especialista.Entity = null;
						previousValue.cita.Remove(this);
					}
					this._especialista.Entity = value;
					if ((value != null))
					{
						value.cita.Add(this);
						this._id_especialista = value.id_especialista;
					}
					else
					{
						this._id_especialista = default(int);
					}
					this.SendPropertyChanged("especialista");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hora_cita_cita", Storage="_hora_cita", ThisKey="id_hora", OtherKey="id_hora", IsForeignKey=true)]
		public hora_cita hora_cita
		{
			get
			{
				return this._hora_cita.Entity;
			}
			set
			{
				hora_cita previousValue = this._hora_cita.Entity;
				if (((previousValue != value) 
							|| (this._hora_cita.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hora_cita.Entity = null;
						previousValue.cita.Remove(this);
					}
					this._hora_cita.Entity = value;
					if ((value != null))
					{
						value.cita.Add(this);
						this._id_hora = value.id_hora;
					}
					else
					{
						this._id_hora = default(int);
					}
					this.SendPropertyChanged("hora_cita");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_cita", Storage="_persona", ThisKey="id_persona", OtherKey="id_persona", IsForeignKey=true)]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.cita.Remove(this);
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.cita.Add(this);
						this._id_persona = value.id_persona;
					}
					else
					{
						this._id_persona = default(int);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ciudad")]
	public partial class ciudad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ciudad;
		
		private string _ciudad1;
		
		private EntitySet<ente_salud> _ente_salud;
		
		private EntitySet<especialista> _especialista;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ciudadChanging(int value);
    partial void Onid_ciudadChanged();
    partial void Onciudad1Changing(string value);
    partial void Onciudad1Changed();
    #endregion
		
		public ciudad()
		{
			this._ente_salud = new EntitySet<ente_salud>(new Action<ente_salud>(this.attach_ente_salud), new Action<ente_salud>(this.detach_ente_salud));
			this._especialista = new EntitySet<especialista>(new Action<especialista>(this.attach_especialista), new Action<especialista>(this.detach_especialista));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ciudad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ciudad
		{
			get
			{
				return this._id_ciudad;
			}
			set
			{
				if ((this._id_ciudad != value))
				{
					this.Onid_ciudadChanging(value);
					this.SendPropertyChanging();
					this._id_ciudad = value;
					this.SendPropertyChanged("id_ciudad");
					this.Onid_ciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ciudad", Storage="_ciudad1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ciudad1
		{
			get
			{
				return this._ciudad1;
			}
			set
			{
				if ((this._ciudad1 != value))
				{
					this.Onciudad1Changing(value);
					this.SendPropertyChanging();
					this._ciudad1 = value;
					this.SendPropertyChanged("ciudad1");
					this.Onciudad1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciudad_ente_salud", Storage="_ente_salud", ThisKey="id_ciudad", OtherKey="id_ciudad")]
		public EntitySet<ente_salud> ente_salud
		{
			get
			{
				return this._ente_salud;
			}
			set
			{
				this._ente_salud.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciudad_especialista", Storage="_especialista", ThisKey="id_ciudad", OtherKey="id_ciudad")]
		public EntitySet<especialista> especialista
		{
			get
			{
				return this._especialista;
			}
			set
			{
				this._especialista.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ente_salud(ente_salud entity)
		{
			this.SendPropertyChanging();
			entity.ciudad = this;
		}
		
		private void detach_ente_salud(ente_salud entity)
		{
			this.SendPropertyChanging();
			entity.ciudad = null;
		}
		
		private void attach_especialista(especialista entity)
		{
			this.SendPropertyChanging();
			entity.ciudad = this;
		}
		
		private void detach_especialista(especialista entity)
		{
			this.SendPropertyChanging();
			entity.ciudad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enfermedad")]
	public partial class enfermedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_enfermedad;
		
		private string _nombre;
		
		private string _descripcion;
		
		private int _id_sintoma;
		
		private int _id_recomendacion;
		
		private EntitySet<sintoma_enfermedad> _sintoma_enfermedad;
		
		private EntityRef<recomendacion> _recomendacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_enfermedadChanging(int value);
    partial void Onid_enfermedadChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onid_sintomaChanging(int value);
    partial void Onid_sintomaChanged();
    partial void Onid_recomendacionChanging(int value);
    partial void Onid_recomendacionChanged();
    #endregion
		
		public enfermedad()
		{
			this._sintoma_enfermedad = new EntitySet<sintoma_enfermedad>(new Action<sintoma_enfermedad>(this.attach_sintoma_enfermedad), new Action<sintoma_enfermedad>(this.detach_sintoma_enfermedad));
			this._recomendacion = default(EntityRef<recomendacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_enfermedad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_enfermedad
		{
			get
			{
				return this._id_enfermedad;
			}
			set
			{
				if ((this._id_enfermedad != value))
				{
					this.Onid_enfermedadChanging(value);
					this.SendPropertyChanging();
					this._id_enfermedad = value;
					this.SendPropertyChanged("id_enfermedad");
					this.Onid_enfermedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sintoma", DbType="Int NOT NULL")]
		public int id_sintoma
		{
			get
			{
				return this._id_sintoma;
			}
			set
			{
				if ((this._id_sintoma != value))
				{
					this.Onid_sintomaChanging(value);
					this.SendPropertyChanging();
					this._id_sintoma = value;
					this.SendPropertyChanged("id_sintoma");
					this.Onid_sintomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_recomendacion", DbType="Int NOT NULL")]
		public int id_recomendacion
		{
			get
			{
				return this._id_recomendacion;
			}
			set
			{
				if ((this._id_recomendacion != value))
				{
					if (this._recomendacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_recomendacionChanging(value);
					this.SendPropertyChanging();
					this._id_recomendacion = value;
					this.SendPropertyChanged("id_recomendacion");
					this.Onid_recomendacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enfermedad_sintoma_enfermedad", Storage="_sintoma_enfermedad", ThisKey="id_enfermedad", OtherKey="id_enfermedad")]
		public EntitySet<sintoma_enfermedad> sintoma_enfermedad
		{
			get
			{
				return this._sintoma_enfermedad;
			}
			set
			{
				this._sintoma_enfermedad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="recomendacion_enfermedad", Storage="_recomendacion", ThisKey="id_recomendacion", OtherKey="id_recomendacion", IsForeignKey=true)]
		public recomendacion recomendacion
		{
			get
			{
				return this._recomendacion.Entity;
			}
			set
			{
				recomendacion previousValue = this._recomendacion.Entity;
				if (((previousValue != value) 
							|| (this._recomendacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._recomendacion.Entity = null;
						previousValue.enfermedad.Remove(this);
					}
					this._recomendacion.Entity = value;
					if ((value != null))
					{
						value.enfermedad.Add(this);
						this._id_recomendacion = value.id_recomendacion;
					}
					else
					{
						this._id_recomendacion = default(int);
					}
					this.SendPropertyChanged("recomendacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sintoma_enfermedad(sintoma_enfermedad entity)
		{
			this.SendPropertyChanging();
			entity.enfermedad = this;
		}
		
		private void detach_sintoma_enfermedad(sintoma_enfermedad entity)
		{
			this.SendPropertyChanging();
			entity.enfermedad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ente_salud")]
	public partial class ente_salud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ente;
		
		private System.Nullable<int> _id_persona;
		
		private int _nit;
		
		private string _razon_social;
		
		private string _representante;
		
		private string _correo;
		
		private string _telefono;
		
		private string _sitio_web;
		
		private int _id_ciudad;
		
		private int _capacidad_pacientes;
		
		private EntitySet<especialista> _especialista;
		
		private EntityRef<ciudad> _ciudad;
		
		private EntityRef<persona> _persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_enteChanging(int value);
    partial void Onid_enteChanged();
    partial void Onid_personaChanging(System.Nullable<int> value);
    partial void Onid_personaChanged();
    partial void OnnitChanging(int value);
    partial void OnnitChanged();
    partial void Onrazon_socialChanging(string value);
    partial void Onrazon_socialChanged();
    partial void OnrepresentanteChanging(string value);
    partial void OnrepresentanteChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Onsitio_webChanging(string value);
    partial void Onsitio_webChanged();
    partial void Onid_ciudadChanging(int value);
    partial void Onid_ciudadChanged();
    partial void Oncapacidad_pacientesChanging(int value);
    partial void Oncapacidad_pacientesChanged();
    #endregion
		
		public ente_salud()
		{
			this._especialista = new EntitySet<especialista>(new Action<especialista>(this.attach_especialista), new Action<especialista>(this.detach_especialista));
			this._ciudad = default(EntityRef<ciudad>);
			this._persona = default(EntityRef<persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ente
		{
			get
			{
				return this._id_ente;
			}
			set
			{
				if ((this._id_ente != value))
				{
					this.Onid_enteChanging(value);
					this.SendPropertyChanging();
					this._id_ente = value;
					this.SendPropertyChanged("id_ente");
					this.Onid_enteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persona", DbType="Int")]
		public System.Nullable<int> id_persona
		{
			get
			{
				return this._id_persona;
			}
			set
			{
				if ((this._id_persona != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_personaChanging(value);
					this.SendPropertyChanging();
					this._id_persona = value;
					this.SendPropertyChanged("id_persona");
					this.Onid_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit", DbType="Int NOT NULL")]
		public int nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				if ((this._nit != value))
				{
					this.OnnitChanging(value);
					this.SendPropertyChanging();
					this._nit = value;
					this.SendPropertyChanged("nit");
					this.OnnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razon_social", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string razon_social
		{
			get
			{
				return this._razon_social;
			}
			set
			{
				if ((this._razon_social != value))
				{
					this.Onrazon_socialChanging(value);
					this.SendPropertyChanging();
					this._razon_social = value;
					this.SendPropertyChanged("razon_social");
					this.Onrazon_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_representante", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string representante
		{
			get
			{
				return this._representante;
			}
			set
			{
				if ((this._representante != value))
				{
					this.OnrepresentanteChanging(value);
					this.SendPropertyChanging();
					this._representante = value;
					this.SendPropertyChanged("representante");
					this.OnrepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitio_web", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sitio_web
		{
			get
			{
				return this._sitio_web;
			}
			set
			{
				if ((this._sitio_web != value))
				{
					this.Onsitio_webChanging(value);
					this.SendPropertyChanging();
					this._sitio_web = value;
					this.SendPropertyChanged("sitio_web");
					this.Onsitio_webChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ciudad", DbType="Int NOT NULL")]
		public int id_ciudad
		{
			get
			{
				return this._id_ciudad;
			}
			set
			{
				if ((this._id_ciudad != value))
				{
					if (this._ciudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ciudadChanging(value);
					this.SendPropertyChanging();
					this._id_ciudad = value;
					this.SendPropertyChanged("id_ciudad");
					this.Onid_ciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacidad_pacientes", DbType="Int NOT NULL")]
		public int capacidad_pacientes
		{
			get
			{
				return this._capacidad_pacientes;
			}
			set
			{
				if ((this._capacidad_pacientes != value))
				{
					this.Oncapacidad_pacientesChanging(value);
					this.SendPropertyChanging();
					this._capacidad_pacientes = value;
					this.SendPropertyChanged("capacidad_pacientes");
					this.Oncapacidad_pacientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ente_salud_especialista", Storage="_especialista", ThisKey="id_ente", OtherKey="id_ente")]
		public EntitySet<especialista> especialista
		{
			get
			{
				return this._especialista;
			}
			set
			{
				this._especialista.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciudad_ente_salud", Storage="_ciudad", ThisKey="id_ciudad", OtherKey="id_ciudad", IsForeignKey=true)]
		public ciudad ciudad
		{
			get
			{
				return this._ciudad.Entity;
			}
			set
			{
				ciudad previousValue = this._ciudad.Entity;
				if (((previousValue != value) 
							|| (this._ciudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ciudad.Entity = null;
						previousValue.ente_salud.Remove(this);
					}
					this._ciudad.Entity = value;
					if ((value != null))
					{
						value.ente_salud.Add(this);
						this._id_ciudad = value.id_ciudad;
					}
					else
					{
						this._id_ciudad = default(int);
					}
					this.SendPropertyChanged("ciudad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_ente_salud", Storage="_persona", ThisKey="id_persona", OtherKey="id_persona", IsForeignKey=true)]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.ente_salud.Remove(this);
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.ente_salud.Add(this);
						this._id_persona = value.id_persona;
					}
					else
					{
						this._id_persona = default(Nullable<int>);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_especialista(especialista entity)
		{
			this.SendPropertyChanging();
			entity.ente_salud = this;
		}
		
		private void detach_especialista(especialista entity)
		{
			this.SendPropertyChanging();
			entity.ente_salud = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.especialidad")]
	public partial class especialidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_especialidad;
		
		private string _especialidad1;
		
		private EntitySet<especialista> _especialista;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_especialidadChanging(int value);
    partial void Onid_especialidadChanged();
    partial void Onespecialidad1Changing(string value);
    partial void Onespecialidad1Changed();
    #endregion
		
		public especialidad()
		{
			this._especialista = new EntitySet<especialista>(new Action<especialista>(this.attach_especialista), new Action<especialista>(this.detach_especialista));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especialidad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_especialidad
		{
			get
			{
				return this._id_especialidad;
			}
			set
			{
				if ((this._id_especialidad != value))
				{
					this.Onid_especialidadChanging(value);
					this.SendPropertyChanging();
					this._id_especialidad = value;
					this.SendPropertyChanged("id_especialidad");
					this.Onid_especialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="especialidad", Storage="_especialidad1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string especialidad1
		{
			get
			{
				return this._especialidad1;
			}
			set
			{
				if ((this._especialidad1 != value))
				{
					this.Onespecialidad1Changing(value);
					this.SendPropertyChanging();
					this._especialidad1 = value;
					this.SendPropertyChanged("especialidad1");
					this.Onespecialidad1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="especialidad_especialista", Storage="_especialista", ThisKey="id_especialidad", OtherKey="id_especialidad")]
		public EntitySet<especialista> especialista
		{
			get
			{
				return this._especialista;
			}
			set
			{
				this._especialista.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_especialista(especialista entity)
		{
			this.SendPropertyChanging();
			entity.especialidad = this;
		}
		
		private void detach_especialista(especialista entity)
		{
			this.SendPropertyChanging();
			entity.especialidad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.especialista")]
	public partial class especialista : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_especialista;
		
		private System.Nullable<int> _id_ente;
		
		private string _nombre;
		
		private string _correo;
		
		private string _celular;
		
		private int _id_especialidad;
		
		private int _id_ciudad;
		
		private int _num_licencia;
		
		private System.DateTime _fech_expedicion_licen;
		
		private EntitySet<cita> _cita;
		
		private EntityRef<ciudad> _ciudad;
		
		private EntityRef<ente_salud> _ente_salud;
		
		private EntityRef<especialidad> _especialidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_especialistaChanging(int value);
    partial void Onid_especialistaChanged();
    partial void Onid_enteChanging(System.Nullable<int> value);
    partial void Onid_enteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void Onid_especialidadChanging(int value);
    partial void Onid_especialidadChanged();
    partial void Onid_ciudadChanging(int value);
    partial void Onid_ciudadChanged();
    partial void Onnum_licenciaChanging(int value);
    partial void Onnum_licenciaChanged();
    partial void Onfech_expedicion_licenChanging(System.DateTime value);
    partial void Onfech_expedicion_licenChanged();
    #endregion
		
		public especialista()
		{
			this._cita = new EntitySet<cita>(new Action<cita>(this.attach_cita), new Action<cita>(this.detach_cita));
			this._ciudad = default(EntityRef<ciudad>);
			this._ente_salud = default(EntityRef<ente_salud>);
			this._especialidad = default(EntityRef<especialidad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especialista", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_especialista
		{
			get
			{
				return this._id_especialista;
			}
			set
			{
				if ((this._id_especialista != value))
				{
					this.Onid_especialistaChanging(value);
					this.SendPropertyChanging();
					this._id_especialista = value;
					this.SendPropertyChanged("id_especialista");
					this.Onid_especialistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ente", DbType="Int")]
		public System.Nullable<int> id_ente
		{
			get
			{
				return this._id_ente;
			}
			set
			{
				if ((this._id_ente != value))
				{
					if (this._ente_salud.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enteChanging(value);
					this.SendPropertyChanging();
					this._id_ente = value;
					this.SendPropertyChanged("id_ente");
					this.Onid_enteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_especialidad", DbType="Int NOT NULL")]
		public int id_especialidad
		{
			get
			{
				return this._id_especialidad;
			}
			set
			{
				if ((this._id_especialidad != value))
				{
					if (this._especialidad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_especialidadChanging(value);
					this.SendPropertyChanging();
					this._id_especialidad = value;
					this.SendPropertyChanged("id_especialidad");
					this.Onid_especialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ciudad", DbType="Int NOT NULL")]
		public int id_ciudad
		{
			get
			{
				return this._id_ciudad;
			}
			set
			{
				if ((this._id_ciudad != value))
				{
					if (this._ciudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ciudadChanging(value);
					this.SendPropertyChanging();
					this._id_ciudad = value;
					this.SendPropertyChanged("id_ciudad");
					this.Onid_ciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_licencia", DbType="Int NOT NULL")]
		public int num_licencia
		{
			get
			{
				return this._num_licencia;
			}
			set
			{
				if ((this._num_licencia != value))
				{
					this.Onnum_licenciaChanging(value);
					this.SendPropertyChanging();
					this._num_licencia = value;
					this.SendPropertyChanged("num_licencia");
					this.Onnum_licenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fech_expedicion_licen", DbType="Date NOT NULL")]
		public System.DateTime fech_expedicion_licen
		{
			get
			{
				return this._fech_expedicion_licen;
			}
			set
			{
				if ((this._fech_expedicion_licen != value))
				{
					this.Onfech_expedicion_licenChanging(value);
					this.SendPropertyChanging();
					this._fech_expedicion_licen = value;
					this.SendPropertyChanged("fech_expedicion_licen");
					this.Onfech_expedicion_licenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="especialista_cita", Storage="_cita", ThisKey="id_especialista", OtherKey="id_especialista")]
		public EntitySet<cita> cita
		{
			get
			{
				return this._cita;
			}
			set
			{
				this._cita.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciudad_especialista", Storage="_ciudad", ThisKey="id_ciudad", OtherKey="id_ciudad", IsForeignKey=true)]
		public ciudad ciudad
		{
			get
			{
				return this._ciudad.Entity;
			}
			set
			{
				ciudad previousValue = this._ciudad.Entity;
				if (((previousValue != value) 
							|| (this._ciudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ciudad.Entity = null;
						previousValue.especialista.Remove(this);
					}
					this._ciudad.Entity = value;
					if ((value != null))
					{
						value.especialista.Add(this);
						this._id_ciudad = value.id_ciudad;
					}
					else
					{
						this._id_ciudad = default(int);
					}
					this.SendPropertyChanged("ciudad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ente_salud_especialista", Storage="_ente_salud", ThisKey="id_ente", OtherKey="id_ente", IsForeignKey=true)]
		public ente_salud ente_salud
		{
			get
			{
				return this._ente_salud.Entity;
			}
			set
			{
				ente_salud previousValue = this._ente_salud.Entity;
				if (((previousValue != value) 
							|| (this._ente_salud.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ente_salud.Entity = null;
						previousValue.especialista.Remove(this);
					}
					this._ente_salud.Entity = value;
					if ((value != null))
					{
						value.especialista.Add(this);
						this._id_ente = value.id_ente;
					}
					else
					{
						this._id_ente = default(Nullable<int>);
					}
					this.SendPropertyChanged("ente_salud");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="especialidad_especialista", Storage="_especialidad", ThisKey="id_especialidad", OtherKey="id_especialidad", IsForeignKey=true)]
		public especialidad especialidad
		{
			get
			{
				return this._especialidad.Entity;
			}
			set
			{
				especialidad previousValue = this._especialidad.Entity;
				if (((previousValue != value) 
							|| (this._especialidad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._especialidad.Entity = null;
						previousValue.especialista.Remove(this);
					}
					this._especialidad.Entity = value;
					if ((value != null))
					{
						value.especialista.Add(this);
						this._id_especialidad = value.id_especialidad;
					}
					else
					{
						this._id_especialidad = default(int);
					}
					this.SendPropertyChanged("especialidad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cita(cita entity)
		{
			this.SendPropertyChanging();
			entity.especialista = this;
		}
		
		private void detach_cita(cita entity)
		{
			this.SendPropertyChanging();
			entity.especialista = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hora_cita")]
	public partial class hora_cita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hora;
		
		private System.TimeSpan _hora;
		
		private EntitySet<cita> _cita;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_horaChanging(int value);
    partial void Onid_horaChanged();
    partial void OnhoraChanging(System.TimeSpan value);
    partial void OnhoraChanged();
    #endregion
		
		public hora_cita()
		{
			this._cita = new EntitySet<cita>(new Action<cita>(this.attach_cita), new Action<cita>(this.detach_cita));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hora", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hora
		{
			get
			{
				return this._id_hora;
			}
			set
			{
				if ((this._id_hora != value))
				{
					this.Onid_horaChanging(value);
					this.SendPropertyChanging();
					this._id_hora = value;
					this.SendPropertyChanged("id_hora");
					this.Onid_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time NOT NULL")]
		public System.TimeSpan hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hora_cita_cita", Storage="_cita", ThisKey="id_hora", OtherKey="id_hora")]
		public EntitySet<cita> cita
		{
			get
			{
				return this._cita;
			}
			set
			{
				this._cita.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cita(cita entity)
		{
			this.SendPropertyChanging();
			entity.hora_cita = this;
		}
		
		private void detach_cita(cita entity)
		{
			this.SendPropertyChanging();
			entity.hora_cita = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.persona")]
	public partial class persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_persona;
		
		private int _id_rol;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _correo;
		
		private string _celular;
		
		private int _cedula;
		
		private string _password;
		
		private EntitySet<cita> _cita;
		
		private EntitySet<ente_salud> _ente_salud;
		
		private EntityRef<rol> _rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_personaChanging(int value);
    partial void Onid_personaChanged();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OncedulaChanging(int value);
    partial void OncedulaChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public persona()
		{
			this._cita = new EntitySet<cita>(new Action<cita>(this.attach_cita), new Action<cita>(this.detach_cita));
			this._ente_salud = new EntitySet<ente_salud>(new Action<ente_salud>(this.attach_ente_salud), new Action<ente_salud>(this.detach_ente_salud));
			this._rol = default(EntityRef<rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_persona
		{
			get
			{
				return this._id_persona;
			}
			set
			{
				if ((this._id_persona != value))
				{
					this.Onid_personaChanging(value);
					this.SendPropertyChanging();
					this._id_persona = value;
					this.SendPropertyChanged("id_persona");
					this.Onid_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					if (this._rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(50)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int NOT NULL")]
		public int cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_cita", Storage="_cita", ThisKey="id_persona", OtherKey="id_persona")]
		public EntitySet<cita> cita
		{
			get
			{
				return this._cita;
			}
			set
			{
				this._cita.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_ente_salud", Storage="_ente_salud", ThisKey="id_persona", OtherKey="id_persona")]
		public EntitySet<ente_salud> ente_salud
		{
			get
			{
				return this._ente_salud;
			}
			set
			{
				this._ente_salud.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rol_persona", Storage="_rol", ThisKey="id_rol", OtherKey="id_rol", IsForeignKey=true)]
		public rol rol
		{
			get
			{
				return this._rol.Entity;
			}
			set
			{
				rol previousValue = this._rol.Entity;
				if (((previousValue != value) 
							|| (this._rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._rol.Entity = null;
						previousValue.persona.Remove(this);
					}
					this._rol.Entity = value;
					if ((value != null))
					{
						value.persona.Add(this);
						this._id_rol = value.id_rol;
					}
					else
					{
						this._id_rol = default(int);
					}
					this.SendPropertyChanged("rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cita(cita entity)
		{
			this.SendPropertyChanging();
			entity.persona = this;
		}
		
		private void detach_cita(cita entity)
		{
			this.SendPropertyChanging();
			entity.persona = null;
		}
		
		private void attach_ente_salud(ente_salud entity)
		{
			this.SendPropertyChanging();
			entity.persona = this;
		}
		
		private void detach_ente_salud(ente_salud entity)
		{
			this.SendPropertyChanging();
			entity.persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.recomendacion")]
	public partial class recomendacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_recomendacion;
		
		private string _recomendacion1;
		
		private EntitySet<enfermedad> _enfermedad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_recomendacionChanging(int value);
    partial void Onid_recomendacionChanged();
    partial void Onrecomendacion1Changing(string value);
    partial void Onrecomendacion1Changed();
    #endregion
		
		public recomendacion()
		{
			this._enfermedad = new EntitySet<enfermedad>(new Action<enfermedad>(this.attach_enfermedad), new Action<enfermedad>(this.detach_enfermedad));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_recomendacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_recomendacion
		{
			get
			{
				return this._id_recomendacion;
			}
			set
			{
				if ((this._id_recomendacion != value))
				{
					this.Onid_recomendacionChanging(value);
					this.SendPropertyChanging();
					this._id_recomendacion = value;
					this.SendPropertyChanged("id_recomendacion");
					this.Onid_recomendacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="recomendacion", Storage="_recomendacion1", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string recomendacion1
		{
			get
			{
				return this._recomendacion1;
			}
			set
			{
				if ((this._recomendacion1 != value))
				{
					this.Onrecomendacion1Changing(value);
					this.SendPropertyChanging();
					this._recomendacion1 = value;
					this.SendPropertyChanged("recomendacion1");
					this.Onrecomendacion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="recomendacion_enfermedad", Storage="_enfermedad", ThisKey="id_recomendacion", OtherKey="id_recomendacion")]
		public EntitySet<enfermedad> enfermedad
		{
			get
			{
				return this._enfermedad;
			}
			set
			{
				this._enfermedad.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enfermedad(enfermedad entity)
		{
			this.SendPropertyChanging();
			entity.recomendacion = this;
		}
		
		private void detach_enfermedad(enfermedad entity)
		{
			this.SendPropertyChanging();
			entity.recomendacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rol")]
	public partial class rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rol;
		
		private string _rol1;
		
		private EntitySet<persona> _persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    partial void Onrol1Changing(string value);
    partial void Onrol1Changed();
    #endregion
		
		public rol()
		{
			this._persona = new EntitySet<persona>(new Action<persona>(this.attach_persona), new Action<persona>(this.detach_persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="rol", Storage="_rol1", DbType="VarChar(50)")]
		public string rol1
		{
			get
			{
				return this._rol1;
			}
			set
			{
				if ((this._rol1 != value))
				{
					this.Onrol1Changing(value);
					this.SendPropertyChanging();
					this._rol1 = value;
					this.SendPropertyChanged("rol1");
					this.Onrol1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rol_persona", Storage="_persona", ThisKey="id_rol", OtherKey="id_rol")]
		public EntitySet<persona> persona
		{
			get
			{
				return this._persona;
			}
			set
			{
				this._persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_persona(persona entity)
		{
			this.SendPropertyChanging();
			entity.rol = this;
		}
		
		private void detach_persona(persona entity)
		{
			this.SendPropertyChanging();
			entity.rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sintoma")]
	public partial class sintoma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sintoma;
		
		private string _sintoma1;
		
		private EntitySet<sintoma_enfermedad> _sintoma_enfermedad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sintomaChanging(int value);
    partial void Onid_sintomaChanged();
    partial void Onsintoma1Changing(string value);
    partial void Onsintoma1Changed();
    #endregion
		
		public sintoma()
		{
			this._sintoma_enfermedad = new EntitySet<sintoma_enfermedad>(new Action<sintoma_enfermedad>(this.attach_sintoma_enfermedad), new Action<sintoma_enfermedad>(this.detach_sintoma_enfermedad));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sintoma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sintoma
		{
			get
			{
				return this._id_sintoma;
			}
			set
			{
				if ((this._id_sintoma != value))
				{
					this.Onid_sintomaChanging(value);
					this.SendPropertyChanging();
					this._id_sintoma = value;
					this.SendPropertyChanged("id_sintoma");
					this.Onid_sintomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sintoma", Storage="_sintoma1", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string sintoma1
		{
			get
			{
				return this._sintoma1;
			}
			set
			{
				if ((this._sintoma1 != value))
				{
					this.Onsintoma1Changing(value);
					this.SendPropertyChanging();
					this._sintoma1 = value;
					this.SendPropertyChanged("sintoma1");
					this.Onsintoma1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sintoma_sintoma_enfermedad", Storage="_sintoma_enfermedad", ThisKey="id_sintoma", OtherKey="id_sintoma")]
		public EntitySet<sintoma_enfermedad> sintoma_enfermedad
		{
			get
			{
				return this._sintoma_enfermedad;
			}
			set
			{
				this._sintoma_enfermedad.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sintoma_enfermedad(sintoma_enfermedad entity)
		{
			this.SendPropertyChanging();
			entity.sintoma = this;
		}
		
		private void detach_sintoma_enfermedad(sintoma_enfermedad entity)
		{
			this.SendPropertyChanging();
			entity.sintoma = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sintoma_enfermedad")]
	public partial class sintoma_enfermedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sintoma_enfermedad;
		
		private int _id_sintoma;
		
		private int _id_enfermedad;
		
		private EntityRef<enfermedad> _enfermedad;
		
		private EntityRef<sintoma> _sintoma;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sintoma_enfermedadChanging(int value);
    partial void Onid_sintoma_enfermedadChanged();
    partial void Onid_sintomaChanging(int value);
    partial void Onid_sintomaChanged();
    partial void Onid_enfermedadChanging(int value);
    partial void Onid_enfermedadChanged();
    #endregion
		
		public sintoma_enfermedad()
		{
			this._enfermedad = default(EntityRef<enfermedad>);
			this._sintoma = default(EntityRef<sintoma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sintoma_enfermedad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_sintoma_enfermedad
		{
			get
			{
				return this._id_sintoma_enfermedad;
			}
			set
			{
				if ((this._id_sintoma_enfermedad != value))
				{
					this.Onid_sintoma_enfermedadChanging(value);
					this.SendPropertyChanging();
					this._id_sintoma_enfermedad = value;
					this.SendPropertyChanged("id_sintoma_enfermedad");
					this.Onid_sintoma_enfermedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sintoma", DbType="Int NOT NULL")]
		public int id_sintoma
		{
			get
			{
				return this._id_sintoma;
			}
			set
			{
				if ((this._id_sintoma != value))
				{
					if (this._sintoma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_sintomaChanging(value);
					this.SendPropertyChanging();
					this._id_sintoma = value;
					this.SendPropertyChanged("id_sintoma");
					this.Onid_sintomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_enfermedad", DbType="Int NOT NULL")]
		public int id_enfermedad
		{
			get
			{
				return this._id_enfermedad;
			}
			set
			{
				if ((this._id_enfermedad != value))
				{
					if (this._enfermedad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_enfermedadChanging(value);
					this.SendPropertyChanging();
					this._id_enfermedad = value;
					this.SendPropertyChanged("id_enfermedad");
					this.Onid_enfermedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enfermedad_sintoma_enfermedad", Storage="_enfermedad", ThisKey="id_enfermedad", OtherKey="id_enfermedad", IsForeignKey=true)]
		public enfermedad enfermedad
		{
			get
			{
				return this._enfermedad.Entity;
			}
			set
			{
				enfermedad previousValue = this._enfermedad.Entity;
				if (((previousValue != value) 
							|| (this._enfermedad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._enfermedad.Entity = null;
						previousValue.sintoma_enfermedad.Remove(this);
					}
					this._enfermedad.Entity = value;
					if ((value != null))
					{
						value.sintoma_enfermedad.Add(this);
						this._id_enfermedad = value.id_enfermedad;
					}
					else
					{
						this._id_enfermedad = default(int);
					}
					this.SendPropertyChanged("enfermedad");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sintoma_sintoma_enfermedad", Storage="_sintoma", ThisKey="id_sintoma", OtherKey="id_sintoma", IsForeignKey=true)]
		public sintoma sintoma
		{
			get
			{
				return this._sintoma.Entity;
			}
			set
			{
				sintoma previousValue = this._sintoma.Entity;
				if (((previousValue != value) 
							|| (this._sintoma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sintoma.Entity = null;
						previousValue.sintoma_enfermedad.Remove(this);
					}
					this._sintoma.Entity = value;
					if ((value != null))
					{
						value.sintoma_enfermedad.Add(this);
						this._id_sintoma = value.id_sintoma;
					}
					else
					{
						this._id_sintoma = default(int);
					}
					this.SendPropertyChanged("sintoma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaEnfermedad")]
	public partial class VistaEnfermedad
	{
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _sintoma;
		
		private string _recomendacion;
		
		public VistaEnfermedad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintoma", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string sintoma
		{
			get
			{
				return this._sintoma;
			}
			set
			{
				if ((this._sintoma != value))
				{
					this._sintoma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recomendacion", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string recomendacion
		{
			get
			{
				return this._recomendacion;
			}
			set
			{
				if ((this._recomendacion != value))
				{
					this._recomendacion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaEspecialista")]
	public partial class VistaEspecialista
	{
		
		private string _nombre;
		
		private string _ciudad;
		
		private string _especialidad;
		
		private string _correo;
		
		private string _celular;
		
		private int _num_licencia;
		
		private System.DateTime _fech_expedicion_licen;
		
		public VistaEspecialista()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this._ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string especialidad
		{
			get
			{
				return this._especialidad;
			}
			set
			{
				if ((this._especialidad != value))
				{
					this._especialidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this._celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_licencia", DbType="Int NOT NULL")]
		public int num_licencia
		{
			get
			{
				return this._num_licencia;
			}
			set
			{
				if ((this._num_licencia != value))
				{
					this._num_licencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fech_expedicion_licen", DbType="Date NOT NULL")]
		public System.DateTime fech_expedicion_licen
		{
			get
			{
				return this._fech_expedicion_licen;
			}
			set
			{
				if ((this._fech_expedicion_licen != value))
				{
					this._fech_expedicion_licen = value;
				}
			}
		}
	}
	
	public partial class sp_loginResult
	{
		
		private int _id_persona;
		
		private int _id_rol;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _correo;
		
		private string _celular;
		
		private int _cedula;
		
		private string _password;
		
		public sp_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persona", DbType="Int NOT NULL")]
		public int id_persona
		{
			get
			{
				return this._id_persona;
			}
			set
			{
				if ((this._id_persona != value))
				{
					this._id_persona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int NOT NULL")]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this._id_rol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(50)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this._celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int NOT NULL")]
		public int cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
